#If this isn't enabled, the Discounts config file will be ignored
EnableDiscounts: true
#If this isn't enabled, the Sales config file will be ignored
EnableSales: true
#Let Players confirm their Purchase
PurchaseConfirmation: true
#The Player account to which the money will be added after a Purchase. Set to '' to ignore.
ServerAccount: 'j0ach1mmall3'
#The Item configuration in a Category to return to the Shop overview
ReturnItem:
    Name: '&cReturn'
    Description: '&7&oClick here to return to the Shop overview'
    Item: '262'
#The Item configuration for the Confirm Item (will only work if PurchaseConfirmation is enabled)
ConfirmItem:
    Name: '&aConfirm'
    Description: '&7&oClick here to confirm your Purchase'
    Item: '160:13'
#The Item configuration for the Refuse Item (will only work if PurchaseConfirmation is enabled)
RefuseItem:
    Name: '&cRefuse'
    Description: '&7&oClick here to refuse your Purchase'
    Item: '160:14'