name: PermissionsShop
main: com.j0ach1mmall3.permissionsshop.Main
version: 2.1.0
author: j0ach1mmall3
description: Create user friendly GUIs to sell Permissions and more!
depend: [Vault, JLib]
commands:
    PermissionsShop:
        description: Main PermissionsShop command
        usage: /<command> <arguments>
        aliases: ps
permissions:
    permissionsshop.*:
        description: All the PermissionsShop permissions
        default: op
        children:
            permissionsshop.reload: true
    permissionsshop.reload:
        description: Access to /PermissionsShop reload
        default: op